# Copyright (c) 9-7-2024 Cummins Inc
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
version: "3.6"

services:
  target-dev:
    container_name: can-translator-dev-client
    image: can-translator-client-dev
    build:
      context: ../.
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - base
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: base
